// src/views/Calculator.vue
<!-- eslint-disable vue/multi-word-component-names -->
<template>
  <section class="calculator">
    <Container>
      <div class="calculator__content">
        <h2 class="form-title">Калькулятор стоимости ОСАГО</h2>

        <!-- Dropdown для водителей -->
        <h3>Водители</h3>
        <Dropdown v-model="formData.driver" :options="driverOptions" placeholder="Любой водитель" />

        <!-- Dropdown для стажа водителя -->
        <h3>Укажите ваш возраст и водительский стаж <span>*</span></h3>
        <Dropdown
          v-model="formData.driverExperience"
          :options="experienceOptions"
          placeholder="До 25 лет включительно, стаж менее трех лет"
        />

        <!-- Вопрос о диагностической карте -->
        <h3>Есть ли у Вас диагностическая карта техосмотра? <span>*</span></h3>
        <div class="radio-group">
          <label>
            <input type="radio" v-model="formData.diagnosticCard" :value="0.8" />
            Да
          </label>
          <label>
            <input type="radio" v-model="formData.diagnosticCard" :value="1" />
            Нет
          </label>
        </div>

        <!-- Вопрос о предыдущем договоре ОСАГО -->
        <h3>Заключали ли Вы раньше договор ОСАГО? <span>*</span></h3>
        <div class="radio-group">
          <label>
            <!-- поменять value -->
            <input type="radio" v-model="formData.previousAgreement" :value="1" />
            Да
          </label>
          <label>
            <!-- поменять value -->
            <input type="radio" v-model="formData.previousAgreement" :value="0" />
            Нет
          </label>
        </div>

        <!-- Укажите срок страхования -->
        <h3>Укажите срок страхования <span>*</span></h3>
        <div class="insurance-duration">
          <button
            v-for="({
              label, value
            }, index) in insuranceDurations"
            :key="index"
            :class="{ active: formData.insuranceDuration === value }"
            @click="formData.insuranceDuration = value"
          >
            {{ label }}
          </button>
        </div>

        <hr />
        <div class="flex items-center justify-between">
          <h3>Стоимость страхового полиса:</h3>
          <b>2352 сом</b>
        </div>
      </div>
      <Footer :isValid="false" navigateTo="/" />
    </Container>
  </section>
</template>

<script setup>
import Container from '@/components/Container.vue'
import Footer from '@/components/Footer.vue'
import Dropdown from '@/components/Dropdown.vue'
import { reactive, watch } from 'vue'

const driverOptions = [
  {
    label: 'Любой водитель',
    value: 1
  },
  {
    label: 'Конкретные водители',
    value: 2
  }
]
const experienceOptions = [
  {
    label: 'До 25 лет включительно, со стажем вождения до 3 лет включительно',
    value: 1.4
  },
  {
    label: 'До 25 лет включительно, со стажем вождения свыше 3 лет',
    value: 1.3
  },
  {
    label: 'Более 25 лет, со стажем вождения до 3 лет включительно',
    value: 1.2
  },
  {
    label: 'Более 25 лет, со стажем вождения свыше 3 лет',
    value: 1
  }
]

const insuranceDurations = [
  {
    label: 'От 5 до 15 дней',
    value: 0.2
  }, {
    label: 'От 16 дней до 1 месяца',
    value: 0.3
  }, {
    label: 'До 3 месяцев',
    value: 0.5
  }, {
    label: 'До 6 месяцев',
    value: 0.7
  }, {
    label: 'До 9 месяцев',
    value: 0.9
  }, {
    label: 'До 12 месяцев',
    value: 1
  }
]

const formData = reactive({
  driver: null,
  driverExperience: null,
  diagnosticCard: null,
  previousAgreement: null,
  insuranceDuration: 1,
})

watch(
  () => formData,
  () => {
    // НсП = 3%  Потом добавить для расчета
    const calculate = formData.driver + formData.driverExperience + formData.diagnosticCard + formData.previousAgreement + formData.insuranceDuration
    console.log(calculate.toFixed(2));

  }, {
    deep: true
  })

</script>

<style scoped lang="scss">
.calculator {
  @apply py-14;

  &__content {
    @apply space-y-4;

    h3 {
      @apply text-[#040415] font-medium text-[14px];

      span {
        @apply text-[#FC3400];
      }
    }

    .radio-group {
      @apply grid grid-cols-2 space-x-4;

      label {
        @apply flex items-center space-x-2 bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm p-[12px];

        input {
          @apply mr-2;
        }
      }
    }

    .insurance-duration {
      @apply grid grid-cols-4 gap-[8px];

      button {
        @apply px-4 py-2 border rounded-lg text-[12px];

        &.active {
          @apply border-[#005CAA] bg-[#005CAA14];
        }
      }
    }
  }
}

.form-title {
  @apply text-[#000B16] text-[20px] font-semibold mb-4;
}
</style>

// src/pages/Calculator.tsx
import { useEffect, useState } from 'react';
import {
  useCalculateMutation,
  useCreatePolicyMutation,
} from '../store/calculateApi';
import type { IInsuranceData } from '../types';

function getFutureDate(period: string): string {
  const date = new Date();

  switch (period) {
    case '15 дней':
      date.setDate(date.getDate() + 15);
      break;
    case '1 месяц':
      date.setMonth(date.getMonth() + 1);
      break;
    case '3 месяца':
      date.setMonth(date.getMonth() + 3);
      break;
    case '6 месяцев':
      date.setMonth(date.getMonth() + 6);
      break;
    case '9 месяцев':
      date.setMonth(date.getMonth() + 9);
      break;
    case '12 месяцев':
      date.setDate(date.getDate() + 365);
      break;
    default:
      throw new Error('Неподдерживаемый период: ' + period);
  }

  // Отнять один день от результата
  date.setDate(date.getDate() - 1);

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;
}

export default function Calculator() {
  const [calculate, { isLoading: isCalculating, isError: isCalcError }] =
    useCalculateMutation();
  const [createPolicy, { isLoading }] = useCreatePolicyMutation();
  const [coef, setCoef] = useState('');
  const [formData, setFormData] = useState<IInsuranceData>(
    JSON.parse(localStorage.getItem('calculateData') || '{}')
  );
  const [diagnosticCard, setDiagnosticCard] = useState('false');
  const [previousAgreement, setPreviousAgreement] = useState('0');
  const [amount, setAmount] = useState('0');
  const [insuranceDuration, setInsuranceDuration] = useState<string>('12 месяцев');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const isEmpty = (val?: string | null) => !val || val.trim() === '';

  const getInputStyle = (value?: string | null) => ({
    borderColor: isEmpty(value) ? '#ef4444' : '#d1d5db',
  });

  const getData = async (data: IInsuranceData) => {
    try {
      const res = await calculate(data).unwrap();
      if (res) {
        setCoef(res.vehicleTypeCoefficient);
        setAmount(res.amount.toFixed(2));
      } else {
        setCoef('1');
      }
    } catch (err: any) {
      console.log(err);
      setErrorMessage(err.data.keep24);
    }
  };

  useEffect(() => {
    getData(formData);
  }, [formData]);

  useEffect(() => {
    setFormData((prev) => ({
      ...prev,
      endDate: getFutureDate('12 месяцев'),
    }));
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage(null);
    setFormData((prev) => ({
      ...prev,
      vehicleTypeCoefficient: coef,
    }));

    try {
      const res = await createPolicy({
        ...formData,
        phoneNumber: formData.phoneNumber,
        vehicleTypeCoefficient: coef,
      }).unwrap();

      if (
        typeof res === 'object' &&
        res !== null &&
        'result' in res &&
        (res as any).result === 206 &&
        'message' in res
      ) {
        setErrorMessage((res as { message: string }).message);
      } else {
        setErrorMessage(null);
      }
      if (res && 'paymentUrl' in res && typeof res.paymentUrl === 'string') {
        window.open(res.paymentUrl);
      }
      console.log('createPolicy response:', res);
    } catch (err) {
      const errorData = (err as any)?.data;
      if (
        errorData &&
        typeof errorData === 'object' &&
        'result' in errorData &&
        errorData.result === 206 &&
        'message' in errorData
      ) {
        setErrorMessage(errorData.message);
      } else if (errorData && errorData.keep24 && errorData.keep24.message) {
        setErrorMessage(errorData.keep24.message);
      } else {
        setErrorMessage('Произошла ошибка при создании полиса');
      }
      console.log('createPolicy error:', err);
    }
  };

  return (
    <section className='calculator pt-14 pb-5'>
      <form className='max-w-[800px] mx-auto px-4' onSubmit={handleSubmit}>
        <div className='calculator__content space-y-4'>
          <h2 className='text-title text-2xl font-bold'>Калькулятор ОСАГО</h2>
          <h3 className='text-suptitle font-semibold'>
            Есть ли у Вас диагностическая карта?{' '}
            <span className='text-[#FC3400]'>*</span>
          </h3>
          <div className='radio-group grid grid-cols-2 gap-5'>
            <label className='flex items-center bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm p-[12px]'>
              <input
                type='radio'
                value={'true'}
                checked={diagnosticCard === 'true'}
                onChange={() => {
                  setDiagnosticCard('true');
                  setFormData((prev) => {
                    return {
                      ...prev,
                      technicalInspection: true,
                    };
                  });
                }}
                className='mr-2'
              />
              Да
            </label>
            <label className='flex items-center bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm p-[12px]'>
              <input
                type='radio'
                value='false'
                checked={diagnosticCard === 'false'}
                onChange={() => {
                  setDiagnosticCard('false');
                  setFormData((prev) => {
                    return {
                      ...prev,
                      technicalInspection: false,
                    };
                  });
                }}
                className='mr-2'
              />
              Нет
            </label>
          </div>

          {diagnosticCard === 'true' ? (
            <>
              <div className='form-group mt-4'>
                <label className='text-suptitle block' htmlFor='number'>
                  Номер технического осмотра{' '}
                  <span className='required text-red-500'>*</span>
                </label>
                <input
                  required
                  type='text'
                  id='number'
                  placeholder=''
                  className='form-input mt-[12px] w-full bg-[#F7F8FA] rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 border'
                  style={getInputStyle(formData.technicalInspectionNumber)}
                  value={formData.technicalInspectionNumber}
                  onChange={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      technicalInspectionNumber: e.target.value,
                    }))
                  }
                />
              </div>
              <div className='form-group mt-4'>
                <label className='text-suptitle block' htmlFor='date'>
                  Дата выдачи технического осмотра{' '}
                  <span className='required text-red-500'>*</span>
                </label>
                <input
                  required
                  type='date'
                  id='date'
                  className='form-input mt-[12px] w-full bg-[#F7F8FA] rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 border'
                  style={getInputStyle(formData.technicalInspectionIssuingDate)}
                  value={formData.technicalInspectionIssuingDate}
                  onChange={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      technicalInspectionIssuingDate: e.target.value,
                    }))
                  }
                />
              </div>
            </>
          ) : (
            <div></div>
          )}

          <h3 className='text-suptitle font-semibold hidden'>
            Заключали ли Вы раньше договор ОСАГО?{' '}
            <span className='text-[#FC3400]'>*</span>
          </h3>
          <div className='radio-group grid-cols-2 gap-5 hidden'>
            <label className='flex items-center bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm p-[12px]'>
              <input
                type='radio'
                value='1'
                checked={previousAgreement === '1'}
                onChange={() => setPreviousAgreement('1')}
                className='mr-2'
              />
              Да
            </label>
            <label className='flex items-center bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm p-[12px]'>
              <input
                type='radio'
                value='0'
                checked={previousAgreement === '0'}
                onChange={() => setPreviousAgreement('0')}
                className='mr-2'
              />
              Нет
            </label>
          </div>

          <h3 className='text-suptitle font-semibold'>
            Укажите срок страхования <span className='text-[#FC3400]'>*</span>
          </h3>
          <div className='insurance-duration grid grid-cols-3 gap-[8px]'>
            {[
              '15 дней',
              '1 месяц',
              '3 месяца',
              '6 месяцев',
              '9 месяцев',
              '12 месяцев',
            ].map((val) => (
              <div
                key={val}
                onClick={() => {
                  setInsuranceDuration(val);
                  setFormData((prev) => ({
                    ...prev,
                    endDate: getFutureDate(val),
                  }));
                }}
                className={`px-4 py-2 border rounded-lg text-[14px] text-center ${
                  insuranceDuration === val
                    ? 'border-[#005CAA] bg-[#005CAA14]'
                    : ''
                }`}
              >
                {val}
              </div>
            ))}
          </div>
        </div>
        <div className='bg-white mt-[50px]'>
          <div className='flex items-center justify-between border-t-[2px] py-[5px]'>
            <h3>Стоимость:</h3>
            <b className='text-[22px]'>
              {isCalculating
                ? 'Идет рассчет'
                : isCalcError
                ? 'Ошибка при расчете'
                : `${amount} сом`}
            </b>
          </div>
          <footer className='footer w-full mt-[40px]'>
            <div className='footer__content w-full'>
              <button
                type='submit'
                disabled={isLoading}
                className='flex justify-center w-full py-[14px] bg-[#005CAA] rounded-[6px] text-[#fff] text-[16px] mb-[16px] disabled:opacity-50 disabled:cursor-not-allowed'
              >
                {isLoading ? 'Идет рассчет...' : 'Оплатить'}
              </button>
              {errorMessage && (
                <div className='text-red-600 text-sm mt-2 text-center whitespace-pre-line'>
                  {errorMessage}
                </div>
              )}
            </div>
          </footer>
          <p className='text-[12px]'>
            Тут может быть дополнительная информация о цене
          </p>
        </div>
      </form>
    </section>
  );
}
