// src/views/DocumentsForm2.vue
<script setup>
import { computed, ref, reactive, onMounted } from 'vue'
import { useDocumentStore } from '@/stores/useDocumentStore'
import { useOcrStore } from '@/stores/useOcrStore'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'

import Container from '@/components/Container.vue'
import DocumentUploader from '@/components/DocumentUploader.vue'
import Footer from '@/components/Footer.vue'
import loader from '@/assets/icons/loader.vue'

const documentStore = useDocumentStore()
const ocrStore = useOcrStore()
const router = useRouter()

const showReferalInput = ref(false)
const referalId = ref('')

const idDetails = reactive({
  surname: '',
  name: '',
  patronymic: '',
  inn: '',
  number: '',
  issuer: '',
  issueDate: '',
})

onMounted(() => {
  const id = router.currentRoute.value.params.id
  if (id) {
    referalId.value = id
    showReferalInput.value = true
  }

  // ... (остальной сброс и инициализация)

  // Паспорт
  if (ocrStore.passport) {
    idDetails.surname = ocrStore.passport.surname || ''
    idDetails.name = ocrStore.passport.name || ''
    idDetails.patronymic = ocrStore.passport.patronymic || ''
    idDetails.inn = ocrStore.passport.personalNumber || ''
    idDetails.number = ocrStore.passport.documentNumber || ''
    idDetails.issuer = ocrStore.passport.authority || ''
    idDetails.issueDate = ocrStore.passport.issueDate || ''
  }
})
const personalDataChecked = ref(false)
const isDisabled = computed(
  () =>
    !documentStore.areMandatoryDocumentsUploaded2 || loading.value || !personalDataChecked.value,
)
const loading = ref(false)
const { t } = useI18n()

const handleFooterClick = async () => {
  loading.value = true
  try {
    await ocrStore.recognizeAllDocuments(documentStore)
    if (ocrStore.passportError || ocrStore.vehicleCertError) {
      loading.value = false
      return
    }
    ocrStore.saveToLocalStorage()
    router.push('/data-forms-2')
  } catch (e) {
    alert(e.message || 'Ошибка при распознавании документов')
  } finally {
    loading.value = false
  }
}

const documents = computed(() => [
  {
    id: 'passport',
    title: t('documents_form.idPassport'),
    fields: ['passport-front-side', 'passport-back-side'],
  },
  {
    id: 'certificate',
    title: t('documents_form.certificate'),
    fields: ['certificate-front-side', 'certificate-back-side'],
  },
])

const handleFileChange = (event) => {
  const fieldName = event.target.dataset.name
  const selectedFile = event.target.files?.[0]

  if (selectedFile && !['image/jpeg', 'image/png'].includes(selectedFile.type)) {
    alert('Пожалуйста, загрузите изображение в формате JPEG или PNG.')
    return
  }

  const data = selectedFile
    ? { file: selectedFile, url: URL.createObjectURL(selectedFile) }
    : { file: null, url: null }

  documentStore.updateDocument(fieldName, data)
}
</script>

<template>
  <section class="passport">
    <Container>
      <h2 class="text-title">{{ t('documents_form.title') }}</h2>

      <DocumentUploader
        v-for="doc in documents"
        :key="doc.id"
        :title="doc.title"
        :fields="doc.fields.map((field) => ({ field, ...documentStore.uploadedDocuments[field] }))"
        :error="doc.id === 'passport' ? ocrStore.passportError : ocrStore.vehicleCertError"
        @file-change="handleFileChange"
      />

      <div class="form-group">
        <template v-if="!showReferalInput && !referalId">
          <div
            class="text-blue-500 py-2 rounded mb-2 underline text-[13px]"
            type="button"
            @click="showReferalInput = true"
          >
            Указать ID участника (необязательно)
          </div>
        </template>
        <template v-if="showReferalInput || referalId">
          <label for="referal-id" class="text-suptitle">ID участника команды (необязательно)</label>
          <br />
          <input
            type="text"
            placeholder="Введите ID"
            class="form-input mt-[12px]"
            v-model="referalId"
            id="referal-id"
            :readonly="!!referalId && router.currentRoute.value.params.id"
          />
        </template>
      </div>

      <div class="passport__bottom">
        <label>
          <input type="checkbox" v-model="personalDataChecked" />
          {{ t('documents_form.personalData') }}
        </label>
      </div>
      <Footer :isValid="isDisabled" @click="handleFooterClick" :navigateTo="'/data-forms'" />
      <div
        v-if="loading"
        class="fixed z-[10000] top-0 left-0 w-full h-full flex items-center justify-center bg-[rgba(0,0,0,0.5)]"
      >
        <div class="w-[50%] h-[40%] bg-white flex flex-col items-center justify-center rounded">
          <loader class="w-[150px] h-[150px]" />
          <p class="text-center text-[16px]">Идет сканирование документов</p>
        </div>
      </div>
    </Container>
  </section>
</template>

<style lang="scss">
.passport {
  @apply py-14 pb-[100px];

  .form-input {
    @apply w-full bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm px-3 py-2 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500;
  }

  &__title {
    @apply text-[#000B16] text-[20px] font-semibold mb-4;
  }

  &__bottom {
    @apply flex flex-col gap-[20px] mt-[60px];

    label {
      @apply flex items-center gap-[14px] text-[13px];
    }

    span {
      @apply text-[#3D9CEC] underline;
    }

    input {
      appearance: none;
      border: 2px solid #005caa;
      width: 20px;
      height: 20px;
      border-radius: 3px;

      &:checked {
        background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'%3e%3cpath fill='none' stroke='%23005CAA' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' d='M6 10l3 3l6-6'/%3e%3c/svg%3e");
      }
    }
  }
}
</style>

// src/pages/DocumentsForm2.tsx
import React from 'react';
import { useParams, useNavigate  } from 'react-router';
import { useRecognizeDocumentMutation } from '../store/ocrApi';

import passportFrontSide from '../assets/images/passport-front-side.png';
import passportBackSide from '../assets/images/passport-back-side.png';
import tp_front from '../assets/images/tp_front.png';
import tp_back from '../assets/images/tp_back.png';
import loader from '../assets/loader.svg';

const RemoveIcon = ({ onClick }: { onClick: React.MouseEventHandler }) => (
  <svg
    width='20'
    height='21'
    viewBox='0 0 20 21'
    fill='none'
    xmlns='http://www.w3.org/2000/svg'
    className='absolute top-0 right-0 z-[1] bg-white rounded cursor-pointer'
    onClick={onClick}
    style={{ boxShadow: '0 0 2px #0002' }}
  >
    <path
      d='M16.5 4L3.5 17'
      stroke='#E54335'
      strokeWidth='1.3'
      strokeLinecap='round'
      strokeLinejoin='round'
    />
    <path
      d='M3.5 4L16.5 17'
      stroke='#E54335'
      strokeWidth='1.3'
      strokeLinecap='round'
      strokeLinejoin='round'
    />
  </svg>
);

const UploadIcon = () => (
  <svg
    id='Layer_2'
    height='25'
    viewBox='0 0 512 512'
    width='25'
    xmlns='http://www.w3.org/2000/svg'
    data-name='Layer 2'
    className='absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[1]'
  >
    <defs>
      <linearGradient
        id='linear-gradient'
        gradientTransform='matrix(-1 0 0 -1 512 512)'
        gradientUnits='userSpaceOnUse'
        x1='43.93'
        x2='468.07'
        y1='43.93'
        y2='468.07'
      >
        <stop offset='0' stopColor='#2492ff' />
        <stop offset='1' stopColor='#0043ae' />
      </linearGradient>
    </defs>
    <g id='Icon'>
      <g id='_70' data-name='70'>
        <rect
          id='Background'
          fill='url(#linear-gradient)'
          height='512'
          rx='150'
          transform='matrix(-1 0 0 -1 512 512)'
          width='512'
        />
        <g fill='#fff'>
          <path d='m183.47 197.72 47.53 47.53v-129.52c0-13.81 11.19-25 25-25 13.81 0 25 11.19 25 25v129.52l47.53-47.53c9.76-9.76 25.59-9.76 35.36 0 9.76 9.76 9.76 25.59 0 35.36l-90.21 90.21c-9.76 9.76-25.59 9.76-35.36 0l-90.21-90.21c-9.76-9.76-9.76-25.59 0-35.36 9.76-9.76 25.59-9.76 35.36 0z' />
          <rect height='50' rx='25' width='250' x='131' y='371.27' />
        </g>
      </g>
    </g>
  </svg>
);

const DocumentsForm2: React.FC = () => {
  const params = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [recognizeDocument, { isLoading }] =
    useRecognizeDocumentMutation();

  const [passportFront, setPassportFront] = React.useState<File | null>(null);
  const [passportBack, setPassportBack] = React.useState<File | null>(null);
  const [tpFront, setTpFront] = React.useState<File | null>(null);
  const [tpBack, setTpBack] = React.useState<File | null>(null);

  const [personalDataChecked, setPersonalDataChecked] = React.useState(false);
  // Глобальная ошибка больше не нужна
  // const [errorMsg, setErrorMsg] = React.useState<string | null>(null);

  // Состояния ошибок для каждого документа
  const [passportError, setPassportError] = React.useState<string | null>(null);
  const [vehicleError, setVehicleError] = React.useState<string | null>(null);

  // Состояние для таймера
  const [timer, setTimer] = React.useState(30);

  React.useEffect(() => {
    let interval: number | null = null;
    if (isLoading) {
      setTimer(30);
      interval = window.setInterval(() => {
        setTimer((prev) => (prev === 1 ? 30 : prev - 1));
      }, 1000);
    } else {
      setTimer(30);
    }
    return () => {
      if (interval !== null) window.clearInterval(interval);
    };
  }, [isLoading]);

  const isValid = Boolean(
    passportFront && passportBack && tpFront && tpBack && personalDataChecked
  );

  const handleSend = async () => {
    // Сброс ошибок перед отправкой
    setPassportError(null);
    setVehicleError(null);

    if (
      !passportFront ||
      !passportBack ||
      !tpFront ||
      !tpBack ||
      !personalDataChecked
    )
      return;

    let passportRes, vehicleRes;

    // Паспорт
    try {
      passportRes = await recognizeDocument({
        documentType: 'passport',
        front: passportFront,
        back: passportBack,
      }).unwrap();
    } catch (err: any) {
      setPassportError(
        err?.data?.error ||
        err?.error ||
        (typeof err === 'string' ? err : 'Ошибка при загрузке или сканировании документов')
      );
      return;
    }

    // Свидетельство
    try {
      vehicleRes = await recognizeDocument({
        documentType: 'vehicle_cert',
        front: tpFront,
        back: tpBack,
      }).unwrap();
    } catch (err: any) {
      setVehicleError(
        err?.data?.error ||
        err?.error ||
        (typeof err === 'string' ? err : 'Ошибка при загрузке или сканировании документов')
      );
      return;
    }

    localStorage.setItem('ocrData', '{}')

    localStorage.setItem('ocrData', JSON.stringify({
      passport: passportRes.data,
      vehicle_cert: vehicleRes.data
    }));
    navigate('/data-forms-2');
  };

  return (
    <section className='passport py-14 pb-[100px]'>
      <div className='mx-auto px-4 max-w-[1200px]'>
        <h2 className='text-[#000B16] text-[20px] font-semibold mb-4'>
          Загрузка документов
        </h2>

        {/* Блок загрузки паспорта */}
        <div className='mb-[30px]'>
          <h2 className='mb-[12px] text-[16px] font-medium'>Паспорт</h2>
          <div className='grid grid-cols-2 gap-[12px]'>
            {/* Лицевая сторона */}
            <label className='relative flex flex-col cursor-pointer'>
              <div className='relative w-full h-[150px] border border-dashed border-gray-300 rounded overflow-hidden flex items-center justify-center'>
                {passportFront ? (
                  <div className='relative h-full w-full flex items-center justify-center'>
                    <RemoveIcon
                      onClick={(e) => {
                        e.stopPropagation();
                        setPassportFront(null);
                      }}
                    />
                    <img
                      src={URL.createObjectURL(passportFront)}
                      alt=''
                      className='object-contain max-h-full max-w-full'
                    />
                  </div>
                ) : (
                  <div className='relative h-full w-full flex justify-center items-center'>
                    <UploadIcon />
                    <img
                      className='file-upload-image blur-sm object-contain'
                      src={passportFrontSide}
                      alt='Изображение'
                    />
                  </div>
                )}
              </div>
              <div className='text-center mt-2 text-[14px]'>
                Лицевая сторона
              </div>
              <input
                type='file'
                className='hidden'
                onChange={(e) => setPassportFront(e.target.files![0])}
              />
            </label>

            {/* Обратная сторона */}
            <label className='relative flex flex-col cursor-pointer'>
              <div className='relative w-full h-[150px] border border-dashed border-gray-300 rounded overflow-hidden flex items-center justify-center'>
                {passportBack ? (
                  <div className='relative h-full w-full flex items-center justify-center'>
                    <RemoveIcon
                      onClick={(e) => {
                        e.stopPropagation();
                        setPassportBack(null);
                      }}
                    />
                    <img
                      src={URL.createObjectURL(passportBack)}
                      alt=''
                      className='object-contain max-h-full max-w-full'
                    />
                  </div>
                ) : (
                  <div className='relative h-full w-full flex justify-center items-center'>
                    <UploadIcon />
                    <img
                      className='file-upload-image blur-sm object-contain'
                      src={passportBackSide}
                      alt='Изображение'
                    />
                  </div>
                )}
              </div>
              <div className='text-center mt-2 text-[14px]'>
                Обратная сторона
              </div>
              <input
                type='file'
                className='hidden'
                onChange={(e) => setPassportBack(e.target.files![0])}
              />
            </label>
          </div>
          {passportError && (
            <div className='text-red-500 text-center text-[13px] -mt-2 mb-[20px]'>
              {passportError}
            </div>
          )}
        </div>

        {/* Блок загрузки свидетельства */}
        <div className='mb-[30px]'>
          <h2 className='mb-[12px] text-[16px] font-medium'>
            Свидетельство о регистрации ТС
          </h2>
          <div className='grid grid-cols-2 gap-[12px]'>
            {/* Лицевая сторона */}
            <label className='relative flex flex-col cursor-pointer'>
              <div className='relative w-full h-[150px] border border-dashed border-gray-300 rounded overflow-hidden flex items-center justify-center'>
                {tpFront ? (
                  <div className='relative h-full w-full flex items-center justify-center'>
                    <RemoveIcon
                      onClick={(e) => {
                        e.stopPropagation();
                        setTpFront(null);
                      }}
                    />
                    <img
                      src={URL.createObjectURL(tpFront)}
                      alt=''
                      className='object-contain max-h-full max-w-full'
                    />
                  </div>
                ) : (
                  <div className='relative h-full w-full flex justify-center items-center'>
                    <UploadIcon />
                    <img
                      className='file-upload-image blur-sm object-contain'
                      src={tp_front}
                      alt='Изображение'
                    />
                  </div>
                )}
              </div>
              <div className='text-center mt-2 text-[14px]'>
                Лицевая сторона
              </div>
              <input
                type='file'
                className='hidden'
                onChange={(e) => setTpFront(e.target.files![0])}
              />
            </label>

            {/* Обратная сторона */}
            <label className='relative flex flex-col cursor-pointer'>
              <div className='relative w-full h-[150px] border border-dashed border-gray-300 rounded overflow-hidden flex items-center justify-center'>
                {tpBack ? (
                  <div className='relative h-full w-full flex items-center justify-center'>
                    <RemoveIcon
                      onClick={(e) => {
                        e.stopPropagation();
                        setTpBack(null);
                      }}
                    />
                    <img
                      src={URL.createObjectURL(tpBack)}
                      alt=''
                      className='object-contain max-h-full max-w-full'
                    />
                  </div>
                ) : (
                  <div className='relative h-full w-full flex justify-center items-center'>
                    <UploadIcon />
                    <img
                      className='file-upload-image blur-sm object-contain'
                      src={tp_back}
                      alt='Изображение'
                    />
                  </div>
                )}
              </div>
              <div className='text-center mt-2 text-[14px]'>
                Обратная сторона
              </div>
              <input
                type='file'
                className='hidden'
                onChange={(e) => setTpBack(e.target.files![0])}
              />
            </label>
          </div>
          {/* Блок ошибки */}
          {vehicleError && (
            <div className='text-red-500 text-center text-[13px] mt-2 mb-[20px]'>
              {vehicleError}
            </div>
          )}
        </div>

        {/* Блок ввода реферального ID */}
        <div className='form-group mb-6'>
          <div
            className='text-blue-500 py-2 rounded mb-2 underline text-[13px]'
            role='button'
          >
            Указать ID участника (необязательно)
          </div>
          {params.id && (
            <>
              <label htmlFor='referal-id' className='text-[14px] block'>
                ID участника команды (необязательно)
              </label>
              <input
                type='text'
                id='referal-id'
                placeholder='Введите ID'
                className='w-full mt-[12px] bg-[#F7F8FA] border border-gray-300 rounded-md shadow-sm px-3 py-2 focus:outline-none'
              />
            </>
          )}
        </div>
        {/* Чекбокс согласия */}
        <div className='passport__bottom flex flex-col gap-[20px] mt-[60px]'>
          <label className='flex items-center gap-[14px] text-[13px]'>
            <input
              type='checkbox'
              className='appearance-none border-2 border-[#005CAA] w-5 h-5 rounded-[3px] personal-checkbox'
              checked={personalDataChecked}
              onChange={(e) => setPersonalDataChecked(e.target.checked)}
            />
            Согласие на обработку персональных данных
          </label>
        </div>
        {/* Кнопка "Далее" */}
        <div className='w-full mt-[40px]'>
          <button
            type='button'
            disabled={!isValid || isLoading}
            className='flex justify-center w-full py-[14px] bg-[#005CAA] rounded-[6px] text-white text-[16px] mb-[16px] disabled:opacity-50 disabled:cursor-not-allowed'
            onClick={handleSend}
          >
            Далее
          </button>
        </div>
        {/* Модальное окно загрузки */}
        {isLoading && (
          <div className='fixed z-[10000] top-0 left-0 w-full h-full flex items-center justify-center bg-[rgba(0,0,0,0.5)]'>
            <div className='w-[50%] h-[40%] bg-white flex flex-col items-center justify-center rounded'>
              <img src={loader} alt='' />
              <p className='text-center text-[16px] mb-2'>
                Идет сканирование документов
              </p>
              <div className='text-center text-[24px] font-bold text-blue-600'>
                {timer} сек
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default DocumentsForm2;
